name: foodishpedia_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  ionicons: 0.2.1
  firebase_core: 2.4.1
  firebase_auth: 4.2.5
  google_sign_in: 5.4.4
  cloud_firestore: 4.3.1
  flutter_native_splash: ^2.2.17
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_native_splash: 
  background_image: assets/images/foodishpedia.png
  android: true
  ios: true
  web: true

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

