// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2wV-Htawcps_GpJbj5ItVNFvtSc2mYuk',
    appId: '1:937693531269:web:199c918fe757d2b660adec',
    messagingSenderId: '937693531269',
    projectId: 'foodishpedia-apps',
    authDomain: 'foodishpedia-apps.firebaseapp.com',
    storageBucket: 'foodishpedia-apps.appspot.com',
    measurementId: 'G-R90665PEJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbxaPXcYGmmAH5faG8TncprKBTl1nCZxc',
    appId: '1:937693531269:android:b0b118c68b30964460adec',
    messagingSenderId: '937693531269',
    projectId: 'foodishpedia-apps',
    storageBucket: 'foodishpedia-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUF-3c-UG5CdWOiR0gHnGwnDGd7BmHalI',
    appId: '1:937693531269:ios:7f7eea6de86c2a6560adec',
    messagingSenderId: '937693531269',
    projectId: 'foodishpedia-apps',
    storageBucket: 'foodishpedia-apps.appspot.com',
    androidClientId: '937693531269-d3livijul6a4m5t5m6k6fgn1sv9ggsgd.apps.googleusercontent.com',
    iosClientId: '937693531269-ubh5eldk3ql7r9qavsjuakg21cks61tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodishpediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUF-3c-UG5CdWOiR0gHnGwnDGd7BmHalI',
    appId: '1:937693531269:ios:7f7eea6de86c2a6560adec',
    messagingSenderId: '937693531269',
    projectId: 'foodishpedia-apps',
    storageBucket: 'foodishpedia-apps.appspot.com',
    androidClientId: '937693531269-d3livijul6a4m5t5m6k6fgn1sv9ggsgd.apps.googleusercontent.com',
    iosClientId: '937693531269-ubh5eldk3ql7r9qavsjuakg21cks61tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodishpediaApp',
  );
}
